backend:
  replicaCount: 1
  name: backend
  nameOverride: "backend"
  fullnameOverride: "backend"
  image:
    repository: klotzandrew/k99-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

repo:
  replicaCount: 1
  name: repo
  nameOverride: "repo"
  fullnameOverride: "repo"
  image:
    repository: klotzandrew/k99-repo
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

frontend:
  replicaCount: 1
  name: frontend
  nameOverride: "frontend"
  fullnameOverride: "frontend"
  image:
    repository: klotzandrew/k99-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
