apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend-route
  labels:
    app.kubernetes.io/name: {{ include "chart.backend.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - backend
  http:
  - route:
    - destination:
        host: backend
        # subset: v2
      weight: 100
