apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: repo-route
  labels:
    app.kubernetes.io/name: {{ include "chart.repo.name" . }}
    helm.sh/chart: {{ include "chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - repo
  http:
  - route:
    - destination:
        host: repo
        # subset: v2
      weight: 100
